from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schema"
OUT = ROOT / "src" / "generated" / "types.ts"
PY_OUT = ROOT.parents[1] / "services" / "control_plane" / "app" / "generated_contracts.py"


def to_interface_name(title: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", title) or "Schema"


def to_field_name(name: str) -> str:
    return name


def ts_type(
    schema: dict,
    defs: dict,
    interface_by_filename: dict | None = None,
) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].rsplit("/", 1)[-1]
        if interface_by_filename and ref in interface_by_filename:
            return interface_by_filename[ref]
        return to_interface_name(Path(ref).stem)
    if "const" in schema:
        return json.dumps(schema["const"])
    if schema.get("type") == "array":
        return f"{ts_type(schema.get('items', {}), defs, interface_by_filename)}[]"
    if schema.get("type") == "object":
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        lines = ["{"]
        for name, prop in properties.items():
            optional = "" if name in required else "?"
            lines.append(
                f"  {to_field_name(name)}{optional}: {ts_type(prop, defs, interface_by_filename)};"
            )
        lines.append("}")
        return "\n".join(lines)
    type_name = schema.get("type", "unknown")
    if type_name == "string":
        enum = schema.get("enum")
        if enum:
            return " | ".join(json.dumps(item) for item in enum)
        return "string"
    if type_name in ("integer", "number"):
        return "number"
    if type_name == "boolean":
        return "boolean"
    return "unknown"


def generate() -> None:
    schemas: dict[str, dict] = {}
    for path in sorted(SCHEMA_DIR.glob("*.json")):
        schemas[path.name] = json.loads(path.read_text(encoding="utf-8"))
    interface_by_filename = {
        name: to_interface_name(data.get("title") or Path(name).stem)
        for name, data in schemas.items()
    }

    lines = [
        "// Generated by packages/contracts/scripts/generate_types.py; do not edit.",
        "/* eslint-disable */",
        "",
    ]
    for data in schemas.values():
        title = data.get("title")
        if not title:
            continue
        interface = to_interface_name(title)
        required = set(data.get("required", []))
        lines.append(f"export interface {interface} {{")
        for name, prop in data.get("properties", {}).items():
            optional = "" if name in required else "?"
            lines.append(
                f"  {to_field_name(name)}{optional}: {ts_type(prop, data, interface_by_filename)};"
            )
        if data.get("additionalProperties") is True:
            lines.append("  [key: string]: unknown;")
        lines.append("}")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    generate_pydantic(schemas)


def generate_pydantic(schemas: dict[str, dict]) -> None:
    interface_by_filename = {
        name: to_interface_name(data.get("title") or Path(name).stem)
        for name, data in schemas.items()
    }
    lines = [
        "# Generated by packages/contracts/scripts/generate_types.py; do not edit.",
        "from typing import Any, Literal",
        "from pydantic import BaseModel, Field",
        "",
    ]
    for data in schemas.values():
        title = data.get("title")
        if not title:
            continue
        class_name = to_interface_name(title)
        required = set(data.get("required", []))
        lines.append(f"class {class_name}(BaseModel):")
        properties = data.get("properties", {})
        if not properties:
            lines.append("    pass")
            lines.append("")
            continue
        for name, prop in properties.items():
            pyd_type, default = _pydantic_field(prop, interface_by_filename)
            if name in required:
                if default is not _MISSING:
                    lines.append(f"    {name}: {pyd_type} = {default}")
                else:
                    lines.append(f"    {name}: {pyd_type}")
            else:
                if default is not _MISSING:
                    lines.append(f"    {name}: {pyd_type} = {default}")
                else:
                    lines.append(f"    {name}: {pyd_type} | None = None")
        lines.append("")
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.write_text("\n".join(lines), encoding="utf-8")


class _Missing:
    pass


_MISSING = _Missing()


def _pydantic_field(schema: dict, interface_by_filename: dict) -> tuple[str, object]:
    if "$ref" in schema:
        ref = schema["$ref"].rsplit("/", 1)[-1]
        name = interface_by_filename.get(ref, to_interface_name(Path(ref).stem))
        return name, _MISSING
    if "const" in schema:
        value = schema["const"]
        literal = json.dumps(value)
        return f"Literal[{literal}]", literal
    if schema.get("type") == "array":
        item, _ = _pydantic_field(schema.get("items", {}), interface_by_filename)
        return f"list[{item}]", "Field(default_factory=list)"
    if schema.get("type") == "object":
        if schema.get("properties"):
            return "dict[str, Any]", "Field(default_factory=dict)"
        return "dict[str, Any]", "Field(default_factory=dict)"
    type_name = schema.get("type", "unknown")
    if type_name == "string":
        enum = schema.get("enum")
        if enum:
            values = ", ".join(json.dumps(item) for item in enum)
            return f"Literal[{values}]", _MISSING
        return "str", _MISSING
    if type_name == "integer":
        return "int", _MISSING
    if type_name == "number":
        return "float", _MISSING
    if type_name == "boolean":
        return "bool", _MISSING
    return "Any", _MISSING


if __name__ == "__main__":
    generate()
    print(OUT)
