# Generated by packages/contracts/scripts/generate_types.py; do not edit.
from typing import Any, Literal
from pydantic import BaseModel, Field

class CommandEnvelope(BaseModel):
    schemaVersion: Literal[1] = 1
    commandId: str
    commandType: str
    runId: str
    idempotencyKey: str
    requestedAt: str
    payload: dict[str, Any] = Field(default_factory=dict)

class AgentEventEnvelope(BaseModel):
    schemaVersion: Literal[1] = 1
    eventId: str
    eventType: str
    streamId: str
    runId: str
    actor: str
    occurredAt: str
    sequence: int | None = None
    payload: dict[str, Any] = Field(default_factory=dict)

class InferenceProfile(BaseModel):
    providerId: str
    model: str
    endpoint: str
    apiKeyRef: str | None = None
    dataPolicy: Any
    timeoutSeconds: int
    maxContextTokens: int | None = None
    capabilities: dict[str, Any] = Field(default_factory=dict)
    requestOptions: dict[str, Any] = Field(default_factory=dict)

class RuntimeProfile(BaseModel):
    name: Any
    label: str
    dependencies: list[Any] = Field(default_factory=list)

class VeridixConfig(BaseModel):
    version: Literal[1] = 1
    project: dict[str, Any] = Field(default_factory=dict)
    profile: Literal["desktop", "lab", "server", "airgap"]
    runtime: dict[str, Any] = Field(default_factory=dict)
    provider: dict[str, Any] = Field(default_factory=dict)
    security: dict[str, Any] = Field(default_factory=dict)
